# 제로베이스 데이터 취업 스쿨 SQL 과제 1
- 스타벅스 이디야 데이터 분석

### 8문제 총 100점

- 1번 5점
- 2번 5점
- 3번 10점
- 4번 5점
- 5번 15점
- 6번 15점
- 7번 40점
- 8번 5점

### 1 ~ 8번 모두 본 노트북 파일에 답안 작성해서 제출해주세요 :)

---

문제 1.

AWS RDS (MySQL) 에 프로젝트 관련 Database 를 생성하고, 접근 가능한 사용자 계정을 생성하세요.

- Database Name : oneday
- User Name / Password : oneday / 1234

In [1]:
import pandas as pd
# import mysql.connector
import pymysql

In [2]:
aws_remote = pymysql.connect(
    host = 'oneday.c7s88kesazzg.us-east-1.rds.amazonaws.com',
    port = 3306,
    user = 'admin',
    password = 'pinoc0507'
)

In [3]:
pin_cur = aws_remote.cursor()

In [4]:
pin_cur.execute("CREATE DATABASE oneday;")

1

In [5]:
pin_cur.execute("CREATE USER 'oneday'@'%' IDENTIFIED BY '1234';")
for item in pin_cur:
    print(item)

In [6]:
pin_cur.execute("GRANT ALL PRIVILEGES ON oneday.* TO 'oneday'@'%';")
pin_cur.execute("FLUSH PRIVILEGES;")

0

In [7]:
pin_cur.close()
aws_remote.close()

제출 1.
- Database 생성문 조회 결과 : SHOW CREATE DATABASE oneday;
- 사용자 권한 확인 결과 : SHOW GRANT FOR ‘oneday’@‘%’

In [8]:
aws_remote = pymysql.connect(
    host = 'oneday.c7s88kesazzg.us-east-1.rds.amazonaws.com',
    port = 3306,
    user = 'oneday',
    password = '1234',
    database="oneday",
)

pin_cur = aws_remote.cursor()

In [9]:
# Execute the first query
pin_cur.execute('show create database oneday;')
for item in pin_cur:
    print(item)

# Execute the second query
pin_cur.execute("show grants for 'oneday'@'%';")
for item in pin_cur:
    print(item)

('oneday', "CREATE DATABASE `oneday` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */")
('GRANT USAGE ON *.* TO `oneday`@`%`',)
('GRANT ALL PRIVILEGES ON `oneday`.* TO `oneday`@`%`',)

문제 2.

스타벅스 이디야 데이터를 저장할 테이블을 다음의 구조로 생성하세요. (PDF 파일 참고)

In [10]:
# 데이터베이스 oneday를 선택하고 확인
pin_cur.execute("use oneday;")
pin_cur.execute("SELECT DATABASE();")
for item in pin_cur:
        print(item)

# 테이블 COFFEE_BRAND 생성
pin_cur.execute('''
    create table COFFEE_BRAND (
        id int not null auto_increment, 
        name varchar(16),
        primary key (id)
    );
''')

aws_remote.commit()

('oneday',)

In [11]:
# 테이블 COFEE_STORE 생성
pin_cur.execute('''
    create table COFFEE_STORE (
        id int not null auto_increment, 
        brand int,
        name varchar(32),
        gu_name varchar(8),
        address varchar(128),
        lat decimal(16, 14),
        lng decimal(17, 14),
        primary key (id),
        foreign key (brand) references COFFEE_BRAND(id)                
    );
''')
for item in pin_cur:
    print(item)
aws_remote.commit()

문제 3.

Python 코드로 COFFEE_BRAND 데이터를 다음과 같이 입력하고 확인하세요. (PDF 파일 참고)

In [12]:
# Insert data into the coffee_brand table
insert_query = '''
    INSERT INTO COFFEE_BRAND (name)
    VALUES (%s);
'''

# Data to be inserted
data = [
    ('STARBUCKS',),  # Note the comma to create a single-element tuple
    ('EDIYA',),
]

# Execute the insert query for each row of data
pin_cur.executemany(insert_query, data)

aws_remote.commit()

제출 2.
- Table 생성 결과 : Desc COFFEE_BRAND; Desc COFFEE_STORE;

제출 3.
- COFFEE_BRAND 조회 결과 : SELECT * FROM COFFEE_BRAND;

In [13]:
# 제출 2
pin_cur.execute('desc COFFEE_BRAND;')
for item in pin_cur:
    print(item)

('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('name', 'varchar(16)', 'YES', '', None, '')

In [14]:
pin_cur.execute('desc COFFEE_STORE;')
for item in pin_cur:
    print(item)

('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('brand', 'int', 'YES', 'MUL', None, '')
('name', 'varchar(32)', 'YES', '', None, '')
('gu_name', 'varchar(8)', 'YES', '', None, '')
('address', 'varchar(128)', 'YES', '', None, '')
('lat', 'decimal(16,14)', 'YES', '', None, '')
('lng', 'decimal(17,14)', 'YES', '', None, '')

In [15]:
pin_cur.execute("select * from COFFEE_BRAND;")
for item in pin_cur:
    print(item)

(1, 'STARBUCKS')
(2, 'EDIYA')

문제 4.

스타벅스 페이지에 접근하는 코드에서 팝업창이 없는 경우, 팝업창을 닫는 코드에서 에러가 발생합니다. 예외처리 해서 에러
메시지를 출력하고 실행이 중단되지 않도록 수정해주세요.

## 질문?
문제에서 제시된 에러 메시지가 무엇인지 명확하지 않습니다. 스타벅스 페이지에 접근할 때 현재는 팝업창이 존재하지 않으며, 팝업창을 닫는 코드가 포함되어 있지 않아 에러가 없습니다.

In [16]:
import requests

from bs4 import BeautifulSoup
from urllib.request import urlopen

from selenium import webdriver
from selenium.webdriver.common.by import By

# 매장 찾기에서 지역 검색
url = "https://www.starbucks.co.kr/store/store_map.do"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

driver = webdriver.Chrome()
driver.get(url) # 실행 결과 포항시 지도로 나오며 시간이 10초 정도 걸린다.

driver.implicitly_wait(10) # 웹 페이지 전체가 로딩 될 때까지 10초간 대기

# 지역검색 버튼
local_search_btn = driver.find_element(By.CSS_SELECTOR, '#container > div > form > fieldset > div > section > article.find_store_cont > article > header.loca_search > h3 > a')
local_search_btn.click()

# 서울 버튼
driver.implicitly_wait(1) # 혹시 모르니 1초간 대기
seoul_search_btn = driver.find_element(By.CSS_SELECTOR, '#container > div > form > fieldset > div > section > article.find_store_cont > article > article:nth-child(4) > div.loca_step1 > div.loca_step1_cont > ul > li:nth-child(1) > a')
seoul_search_btn.click()

# 전체 버튼
driver.implicitly_wait(1) # 혹시 모르니 1초간 대기
seoulTotal_search_btn = driver.find_element(By.CSS_SELECTOR, '#mCSB_2_container > ul > li:nth-child(1) > a')
seoulTotal_search_btn.click()

driver.implicitly_wait(5) # 혹시 모르니 5초간 대기

In [17]:
sbuck_html = driver.page_source
sbuck_soup = BeautifulSoup(sbuck_html, 'html.parser')
sbuck_map_info = sbuck_soup.select(".quickSearchResultBoxSidoGugun")

문제 5.

Python 코드로 스타벅스 페이지에서 데이터를 가져올때, COFFEE_STORE 테이블에 바로 입력하도록 수정하세요.

- 데이터 세트: 매장 이름, 매장이 위치한 구 이름, 매장 주소, 위도, 경도
- 필요한 데이터를 한세트씩 가져와서 COFFEE_STORE 테이블에 각각INSERT 하도록 합니다.
- 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다.
- 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.

In [18]:
results = sbuck_map_info[0].find_all(class_="quickResultLstCon")

sbuck_name = []
sbuck_lat = []
sbuck_long = []
sbuck_address = []

for shop in results:
    # extract necessary info
    shop_name = shop.get("data-name")
    shop_lat = shop.get("data-lat")
    shop_lng = shop.get("data-long")
    shop_address = shop.find(class_='result_details').text
    shop_address = shop_address.replace('1522-3232', '')
    gu_name = shop_address.split(" ")[1]
    # insert into sql table
    brand = 1
    query = """
        INSERT INTO COFFEE_STORE (brand, name, gu_name, address, lat, lng)
        VALUES (%s, %s, %s, %s, %s, %s)
        """
    values = (brand, shop_name, gu_name, shop_address, float(shop_lat), float(shop_lng))
    
    pin_cur.execute(query, values)

    aws_remote.commit()

driver.quit()

## 참고사항
위 코드에서 `mysql.connector`를 사용하면 실행되던 도중에 계속 `connection lost`라는 에러가 떠서 `pymysql`로 갈아탔음. 

`mysql.connector`를 사용할 때 `cursor` 정의하면서 `buffered=True` 옵션을 주었지만 연결 상태에 대한 에러가 계속 뜬다.

제출 4.
- 팝업 예외처리 코드 & 실행 결과 (ipynb)

제출 5.
- 스타벅스 데이터 관련 코드 & 실행 결과 (ipynb)

In [19]:
# 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다.
pin_cur.execute('select count(name) from COFFEE_STORE;')
aws_remote.commit()
for item in pin_cur:
    print(item)

(615,)

In [20]:
# 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.
pin_cur.execute('select * from COFFEE_STORE limit 10;')
aws_remote.commit()
for item in pin_cur:
    print(item)

(1, 1, '역삼아레나빌딩', '강남구', '서울특별시 강남구 언주로 425 (역삼동)', Decimal('37.50108700000000'), Decimal('127.04306900000000'))
(2, 1, '논현역사거리', '강남구', '서울특별시 강남구 강남대로 538 (논현동)', Decimal('37.51017800000000'), Decimal('127.02222300000000'))
(3, 1, '신사역성일빌딩', '강남구', '서울특별시 강남구 강남대로 584 (논현동)', Decimal('37.51393090000000'), Decimal('127.02060570000000'))
(4, 1, '국기원사거리', '강남구', '서울특별시 강남구 테헤란로 125 (역삼동)', Decimal('37.49951700000000'), Decimal('127.03149500000000'))
(5, 1, '대치재경빌딩', '강남구', '서울특별시 강남구 남부순환로 2947 (대치동)', Decimal('37.49466800000000'), Decimal('127.06258300000000'))
(6, 1, '봉은사역', '강남구', '서울특별시 강남구 봉은사로 619 (삼성동)', Decimal('37.51500000000000'), Decimal('127.06319600000000'))
(7, 1, '압구정윤성빌딩', '강남구', '서울특별시 강남구 논현로 834 (신사동)', Decimal('37.52279340000000'), Decimal('127.02860090000000'))
(8, 1, '코엑스별마당', '강남구', '서울특별시 강남구 영동대로 513 (삼성동)', Decimal('37.51015000000000'), Decimal('127.06027500000000'))
(9, 1, '삼성역섬유센터R', '강남구', '서울특별시 강남구 테헤란로 518 (대치동)', Decimal('37.50775000000000'), Decimal('127.06065100000000'))
(10, 1, '압구정R', '강남구', '서울특별시 강남구 언주로 861 (신사동)', Decimal('37.52736690000000'), Decimal('127.03306100000000'))

In [21]:
# 이디야 매장 검색을 위한 자치구들의 이름을 저장해준다.
pin_cur.execute('select distinct gu_name from COFFEE_STORE;')
gu_list = []
aws_remote.commit()
for item in pin_cur:
    gu_list.append(item[0])

print(gu_list)

['강남구', '강북구', '강서구', '관악구', '광진구', '금천구', '노원구', '도봉구', '동작구', '마포구', '서대문구', '서초구', '성북구', '송파구', '양천구', '영등포구', '은평구', '종로구', '중구', '강동구', '구로구', '동대문구', '성동구', '용산구', '중랑구']

문제 6.

Python 코드로 이디야 페이지에서 데이터를 가져올때, COFFEE_STORE 테이블에 바로 입력하도록 수정하세요.

- 데이터 세트 : 매장 이름, 매장이 위치한 구 이름, 매장 주소, 위도, 경도
- 이디야 페이지에서 검색에 사용할 구 이름은 COFFEE_STORE 에서 중복을 제거하는 쿼리를 사용하여 가져와서 {‘서울 ‘ + 구이름} 형식으로 변환하여 사용하도록 합니다.
- 필요한 데이터를 한 세트씩 가져와서 COFFEE_STORE 테이블에 각각 INSERT 하도록 합니다.
- (주의) COFFEE_STORE 테이블에 입력할 구 이름은 {‘서울 ‘} 이 제거된 구 이름입니다.
- 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다.
- 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.

In [22]:
# 매장 찾기 URL
url = 'https://www.ediya.com/contents/find_store.html'

# URL 열기
driver = webdriver.Chrome()
driver.get(url) # 실행 결과 포항시 지도로 나오며 시간이 3초 정도 걸린다.

driver.implicitly_wait(5) # 웹 페이지 전체가 로딩 될 때까지 5초간 대기

# 팝업창의 주소 탭 클릭
addTab_btn = driver.find_element(By.CSS_SELECTOR, '#contentWrap > div.contents > div > div.store_search_pop > ul > li:nth-child(2) > a')
addTab_btn.click()

# 주소란에 키워드 입력 
driver.find_element(By.ID,"keyword").send_keys('서울 중구')
driver.implicitly_wait(1) # 혹시 모르니 1초간 대기
# 검색 버튼 클릭
search_btn = driver.find_element(By.CSS_SELECTOR, '#keyword_div > form > button')
search_btn.click()
driver.implicitly_wait(1) # 혹시 모르니 1초간 대기

In [23]:
# '중구'와 같은 함정을 피하기 위해 검색어 앞에 '서울'을 붙여준다.
for idx, gu in enumerate(gu_list):
    gu_list[idx]= "서울 " + gu

print(gu_list)

['서울 강남구', '서울 강북구', '서울 강서구', '서울 관악구', '서울 광진구', '서울 금천구', '서울 노원구', '서울 도봉구', '서울 동작구', '서울 마포구', '서울 서대문구', '서울 서초구', '서울 성북구', '서울 송파구', '서울 양천구', '서울 영등포구', '서울 은평구', '서울 종로구', '서울 중구', '서울 강동구', '서울 구로구', '서울 동대문구', '서울 성동구', '서울 용산구', '서울 중랑구']

In [24]:
import time
# URL 열기
driver = webdriver.Chrome()
driver.get(url) # 실행 결과 포항시 지도로 나오며 시간이 10초 정도 걸린다.

driver.implicitly_wait(5) # 웹 페이지 전체가 로딩 될 때까지 5초간 대기

# 팝업창의 주소 탭 클릭
addTab_btn = driver.find_element(By.CSS_SELECTOR, '#contentWrap > div.contents > div > div.store_search_pop > ul > li:nth-child(2) > a')
addTab_btn.click()

# 변수 초기화
ed_name = []
ed_address = []
ed_gu = []
for keywd in gu_list:
    # 주소란에 키워드 입력 
    driver.find_element(By.ID,"keyword").send_keys(keywd)
    time.sleep(1) # 혹시 모르니 1초간 대기
    # 검색 버튼 클릭
    search_btn = driver.find_element(By.CSS_SELECTOR, '#keyword_div > form > button')
    search_btn.click()
    time.sleep(1) # 혹시 모르니 1초간 대기
    # 정보 탐색
    ediya_html = driver.page_source
    ediya_soup = BeautifulSoup(ediya_html, 'html.parser')
    time.sleep(2)
    ediya_map_info = ediya_soup.select("#placesList > li")

    
    # shop_info = ediya_map_info[0].find_all(class_="item")
    for data in ediya_map_info:
        ed_name.append(data.find("dt").text)
        ed_address.append(data.find("dd").text)
        ed_gu.append(data.find("dd").text.split(" ")[1])
    # 주소란 키워드 초기화
    driver.find_element(By.ID,"keyword").clear()
    driver.implicitly_wait(1) # 혹시 모르니 1초간 대기

driver.quit() # 고마웠다, 그리고 다신 보지 말자~

In [25]:
df_ediya_raw = pd.DataFrame(
    {
        'ed-name': ed_name,
        'ed-address': ed_address,
        'ed-gu': ed_gu 
    }
)
df_ediya_raw.head()

       ed-name                   ed-address ed-gu
0      강남YMCA점                   서울 강남구 논현동   강남구
1  강남구청역아이티웨딩점  서울 강남구 학동로 338 (논현동, 강남파라곤)   강남구
2      강남논현학동점      서울 강남구 논현로131길 28 (논현동)   강남구
3        강남대치점   서울 강남구 역삼로 415 (대치동, 성진빌딩)   강남구
4        강남도산점      서울 강남구 도산대로37길 20 (신사동)   강남구

In [26]:
import googlemaps
import numpy as np

gmapKey = 'AIzaSyCEigio6WJCbDOM4CwMRL6K-REMOUe7tKQ'
gmap = googlemaps.Client(key=gmapKey)

df_ediya_raw["lat"] = np.nan
df_ediya_raw["lng"] = np.nan

for idx, rows in df_ediya_raw.iterrows():
    search_word = "서울 이디야"  +  str(rows["ed-name"])
    tmp = gmap.geocode(search_word, language="ko")
    tmp[0].get("formatted_address")
    lat = tmp[0].get("geometry")["location"]["lat"]
    lng = tmp[0].get("geometry")["location"]["lng"]
    
    df_ediya_raw.loc[idx,"lat"] = lat
    df_ediya_raw.loc[idx,"lng"] = lng

df_ediya_raw.head()

       ed-name                   ed-address ed-gu        lat         lng
0      강남YMCA점                   서울 강남구 논현동   강남구  37.509902  127.035706
1  강남구청역아이티웨딩점  서울 강남구 학동로 338 (논현동, 강남파라곤)   강남구  37.516466  127.040419
2      강남논현학동점      서울 강남구 논현로131길 28 (논현동)   강남구  37.520295  127.035946
3        강남대치점   서울 강남구 역삼로 415 (대치동, 성진빌딩)   강남구  37.501434  127.052328
4        강남도산점      서울 강남구 도산대로37길 20 (신사동)   강남구  37.522336  127.031173

In [27]:
brand = 2 # for ediya
for _, shop in df_ediya_raw.iterrows():
    # print(shop[1])
    # break
    # extract necessary info
    shop_name = shop['ed-name']
    shop_lat = shop['lat']
    shop_lng = shop['lng']
    shop_address = shop['ed-address']
    gu_name = shop['ed-gu']
    # insert into sql table
    query = """
        INSERT INTO COFFEE_STORE (brand, name, gu_name, address, lat, lng)
        VALUES (%s, %s, %s, %s, %s, %s)
        """
    values = (brand, shop_name, gu_name, shop_address, float(shop_lat), float(shop_lng))
    
    pin_cur.execute(query, values)

    aws_remote.commit()

제출 6.
- 이디야 데이터 관련 코드 & 실행 결과 (ipynb)

In [28]:
# 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다.
pin_cur.execute('select count(name) from COFFEE_STORE;')
for item in pin_cur:
    print(f'총 매장 개수: {item}')

pin_cur.execute('select count(name) from COFFEE_STORE where brand=2;')
for item in pin_cur:
    print(f'이디야 매장 개수: {item}')

총 매장 개수: (1301,)
이디야 매장 개수: (686,)

In [29]:
# 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.
pin_cur.execute('select * from COFFEE_STORE where brand=2 limit 10;')
for item in pin_cur:
    print(item)

(616, 2, '강남YMCA점', '강남구', '서울 강남구 논현동', Decimal('37.50990180000000'), Decimal('127.03570610000000'))
(617, 2, '강남구청역아이티웨딩점', '강남구', '서울 강남구 학동로 338 (논현동, 강남파라곤)', Decimal('37.51646650000000'), Decimal('127.04041910000000'))
(618, 2, '강남논현학동점', '강남구', '서울 강남구 논현로131길 28 (논현동)', Decimal('37.52029460000000'), Decimal('127.03594570000000'))
(619, 2, '강남대치점', '강남구', '서울 강남구 역삼로 415 (대치동, 성진빌딩)', Decimal('37.50143400000000'), Decimal('127.05232800000000'))
(620, 2, '강남도산점', '강남구', '서울 강남구 도산대로37길 20 (신사동)', Decimal('37.52233600000000'), Decimal('127.03117300000000'))
(621, 2, '강남세곡점', '강남구', '서울 강남구 헌릉로569길 9 (세곡동, 강남지웰파인즈)', Decimal('37.46436190000000'), Decimal('127.10459710000000'))
(622, 2, '강남율현점', '강남구', '서울 강남구 밤고개로21길 8 (율현동, 세곡프라자)', Decimal('37.49666450000000'), Decimal('127.06298040000000'))
(623, 2, '개포동역점', '강남구', '서울 강남구 개포로82길 11 (개포동, 삼우빌딩)', Decimal('37.48852140000000'), Decimal('127.06743250000000'))
(624, 2, '건설회관점', '강남구', '서울 강남구 언주로 711 (논현동)', Decimal('37.51742730000000'), Decimal('127.03440080000000'))
(625, 2, '대청역점', '강남구', '서울 강남구 개포로109길 34 (개포동, 대청프라자)', Decimal('37.49417350000000'), Decimal('127.07762940000000'))

문제 7.

Python 코드에서 다음의 데이터를 쿼리를 사용하여 조회하세요.

- 스타벅스 매장 주요 분포 지역 (매장수가 많은 상위 5개 구이름, 매장 개수 출력)
- 이디야 매장 주요 분포 지역 (매장수가 많은 상위 5개 구이름, 매장 개수 출력)
- 구별 브랜드 각각의 매장 개수 조회 (구이름, 브랜드이름, 매장 개수 출력)
- 구별 브랜드 각각의 매장 개수 조회 (구이름, 스타벅스 매장 개수, 이디야 매장 개수 출력)

In [30]:
# 스타벅스 매장 주요 분포 지역 (매장수가 많은 상위 5개 구이름, 매장 개수 출력)
query = """
    SELECT gu_name, COUNT(name) as store_count 
    FROM COFFEE_STORE 
    WHERE brand = 1 
    GROUP BY gu_name 
    ORDER BY store_count DESC 
    LIMIT 5;
    """
pin_cur.execute(query)
for item in pin_cur:
    print(item)

('강남구', 91)
('중구', 52)
('서초구', 48)
('영등포구', 42)
('종로구', 39)

In [31]:
# 이디야 매장 주요 분포 지역 (매장수가 많은 상위 5개 구이름, 매장 개수 출력)
query = """
    SELECT gu_name, COUNT(name) as store_count 
    FROM COFFEE_STORE 
    WHERE brand = 2 
    GROUP BY gu_name 
    ORDER BY store_count DESC 
    LIMIT 5;
    """
pin_cur.execute(query)
for item in pin_cur:
    print(item)

('강서구', 43)
('강남구', 42)
('마포구', 36)
('종로구', 35)
('영등포구', 34)

In [32]:
# 구별 브랜드 각각의 매장 개수 조회 (구이름, 브랜드이름, 매장 개수 출력)
query = """
    select s.gu_name, b.name, count(s.name) as store_count 
    from COFFEE_STORE s, COFFEE_BRAND b  
    where s.brand = b.id 
    group by s.gu_name, s.brand 
    order by s.gu_name, b.name;
    """
pin_cur.execute(query)
for item in pin_cur:
    print(item)

('강남구', 'EDIYA', 42)
('강남구', 'STARBUCKS', 91)
('강동구', 'EDIYA', 28)
('강동구', 'STARBUCKS', 17)
('강북구', 'EDIYA', 16)
('강북구', 'STARBUCKS', 6)
('강서구', 'EDIYA', 43)
('강서구', 'STARBUCKS', 28)
('관악구', 'EDIYA', 26)
('관악구', 'STARBUCKS', 12)
('광진구', 'EDIYA', 20)
('광진구', 'STARBUCKS', 19)
('구로구', 'EDIYA', 25)
('구로구', 'STARBUCKS', 15)
('금천구', 'EDIYA', 21)
('금천구', 'STARBUCKS', 13)
('노원구', 'EDIYA', 31)
('노원구', 'STARBUCKS', 14)
('도봉구', 'EDIYA', 22)
('도봉구', 'STARBUCKS', 7)
('동대문구', 'EDIYA', 23)
('동대문구', 'STARBUCKS', 13)
('동작구', 'EDIYA', 23)
('동작구', 'STARBUCKS', 11)
('마포구', 'EDIYA', 36)
('마포구', 'STARBUCKS', 37)
('서대문구', 'EDIYA', 22)
('서대문구', 'STARBUCKS', 21)
('서초구', 'EDIYA', 28)
('서초구', 'STARBUCKS', 48)
('성동구', 'EDIYA', 20)
('성동구', 'STARBUCKS', 14)
('성북구', 'EDIYA', 29)
('성북구', 'STARBUCKS', 16)
('송파구', 'EDIYA', 30)
('송파구', 'STARBUCKS', 37)
('양천구', 'EDIYA', 26)
('양천구', 'STARBUCKS', 17)
('영등포구', 'EDIYA', 34)
('영등포구', 'STARBUCKS', 42)
('용산구', 'EDIYA', 13)
('용산구', 'STARBUCKS', 24)
('은평구', 'EDIYA', 29)
('은평구', 'STARBUCKS', 14)
('종로구', 'EDIYA', 35)
('종로구', 'STARBUCKS', 39)
('중구', 'EDIYA', 34)
('중구', 'STARBUCKS', 52)
('중랑구', 'EDIYA', 30)
('중랑구', 'STARBUCKS', 8)

In [33]:
# 구별 브랜드 각각의 매장 개수 조회 (구이름, 스타벅스 매장 개수, 이디야 매장 개수 출력)
query = '''
select sbuck.gu_name, sbuck.count STARBUCKS, ediya.count EDIYA 
from 
    (select gu_name, count(brand) count from COFFEE_STORE WHERE brand = 1 GROUP BY gu_name) sbuck, 
    (select gu_name, count(brand) count from COFFEE_STORE WHERE brand = 2 GROUP BY gu_name) ediya 
where sbuck.gu_name = ediya.gu_name;
'''
pin_cur.execute(query)
for item in pin_cur:
    print(item)

('강남구', 91, 42)
('강북구', 6, 16)
('강서구', 28, 43)
('관악구', 12, 26)
('광진구', 19, 20)
('금천구', 13, 21)
('노원구', 14, 31)
('도봉구', 7, 22)
('동작구', 11, 23)
('마포구', 37, 36)
('서대문구', 21, 22)
('서초구', 48, 28)
('성북구', 16, 29)
('송파구', 37, 30)
('양천구', 17, 26)
('영등포구', 42, 34)
('은평구', 14, 29)
('종로구', 39, 35)
('중구', 52, 34)
('강동구', 17, 28)
('구로구', 15, 25)
('동대문구', 13, 23)
('성동구', 14, 20)
('용산구', 24, 13)
('중랑구', 8, 30)

문제 8.

시각화 프로젝트를 위하여 다음의 규칙으로 쿼리하여 CSV 파일로 저장합니다. (Python 코드로 작업)

- 전체 데이터를 가져오는데, 각 스타벅스 매장별로 이디야 전체 매장정보가 매칭되어 있어야 합니다. (정렬 : s_id, e_id 순)
- 다음의 형식으로 저장되어야 합니다. (브랜드 이름, 칼럼 명 주의)
- 데이터 프레임 출력을 해주세요. 데이터 프레임 미출력시 감점입니다.

In [42]:
query = '''
select * from 
    (select s.id s_id, b.name s_brand, s.name s_name, s.gu_name s_gu, s.address s_address, s.lat s_lat, s.lng s_lng 
    from COFFEE_STORE s, COFFEE_BRAND b 
    where b.id = s.brand and b.name like 'STARBUCKS') sbuck, 
    (select s.id e_id, b.name e_brand, s.name e_name, s.gu_name e_gu, s.address e_address, s.lat e_lat, s.lng e_lng 
    from COFFEE_STORE s, COFFEE_BRAND b 
    where b.id = s.brand and b.name like 'EDIYA') ediya 
order by sbuck.s_id, ediya.e_id;
'''
pin_cur.execute(query)
df = pd.DataFrame(pin_cur)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,616,EDIYA,강남YMCA점,강남구,서울 강남구 논현동,37.50990180000000,127.03570610000000
1,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,617,EDIYA,강남구청역아이티웨딩점,강남구,"서울 강남구 학동로 338 (논현동, 강남파라곤)",37.51646650000000,127.04041910000000
2,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,618,EDIYA,강남논현학동점,강남구,서울 강남구 논현로131길 28 (논현동),37.52029460000000,127.03594570000000
3,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,619,EDIYA,강남대치점,강남구,"서울 강남구 역삼로 415 (대치동, 성진빌딩)",37.50143400000000,127.05232800000000
4,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,620,EDIYA,강남도산점,강남구,서울 강남구 도산대로37길 20 (신사동),37.52233600000000,127.03117300000000

In [43]:
df.columns = [
    's_id', 's_brand', 's_name', 's_gu', 's_address', 's_lat', 's_lng', 'e_id', 'e_brand', 'e_name', 'e_gu', 'e_address', 'e_lat', 'e_lng'
]
df.head()

,s_id,s_brand,s_name,s_gu,s_address,s_lat,s_lng,e_id,e_brand,e_name,e_gu,e_address,e_lat,e_lng
0,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,616,EDIYA,강남YMCA점,강남구,서울 강남구 논현동,37.50990180000000,127.03570610000000
1,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,617,EDIYA,강남구청역아이티웨딩점,강남구,"서울 강남구 학동로 338 (논현동, 강남파라곤)",37.51646650000000,127.04041910000000
2,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,618,EDIYA,강남논현학동점,강남구,서울 강남구 논현로131길 28 (논현동),37.52029460000000,127.03594570000000
3,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,619,EDIYA,강남대치점,강남구,"서울 강남구 역삼로 415 (대치동, 성진빌딩)",37.50143400000000,127.05232800000000
4,1,STARBUCKS,역삼아레나빌딩,강남구,서울특별시 강남구 언주로 425 (역삼동),37.50108700000000,127.04306900000000,620,EDIYA,강남도산점,강남구,서울 강남구 도산대로37길 20 (신사동),37.52233600000000,127.03117300000000

제출 8.
- 시각화 프로젝트 관련 코드 (ipynb), 결과 파일 (csv)

In [44]:
df.to_csv('coffee_data.csv', index = False, encoding = "utf-8")

In [45]:
pin_cur.close()
aws_remote.close()

---